### ISSUE TITLE
Support create smart contracts transactions

### ISSUE THREAD

**Issue by ldasilva-net** [cryptoplease/dart-solana-lib#36]
Hi, 
Does the library currently support creating transactions for smart contracts? Did you have an example?
Thanks!

**Comment by iharobCP** [comment]
Hi @ldasilva-net. Thank you for contacting us.

Currently the library does not support that. We are working hard to make the library more complete. In our next release (which will be hopefully next week) we will be providing mechanisms to create arbitrary instructions and to build a message with them. So if you like, you can create a PR for the requested program or, just write it by using then new API for your own use. 

We will provide examples so that you easily and quickly understand how to write the specific transaction you need.

If you can wait. Then we can try to include such transaction constructor in a future release :)

**Comment by ldasilva-net** [comment]
Thanks a lot @iharobCP and team. I will be waiting for the next release!

**Comment by antoineherzog** [comment]
@ldasilva-net you can check the status of the PR here:
https://github.com/cryptoplease/dart-solana-lib/pull/35

**Comment by antoineherzog** [comment]
@ldasilva-net It has been merged! Your Feedback is welcome.
